version: 0.2

phases: 
    build:
        commands:
            - echo "Build block"
            - echo "Running tests to check if "Congratulations" present in src/App.js file"
            - grep "Congratulations" src/App.js
    post_build:
        commands:
            - echo "Post build phase"
artifacts:
    files:
        - scripts/install_dependencies
        - scripts/start_server
        - scripts/stop_server
        - src/App.js
    discard-paths: yes
