version: 0.2

phases: 
    build:
        commands:
            - echo "Build block"
            - ls
            - echo "Running tests to check if "Congratulations" present in App.js file"
            - grep "Congratulations" App.js
    post_build:
        commands:
            - echo "Post build phase"
artifacts:
    files:
        - scripts/install_dependencies
        - scripts/start_server
        - scripts/stop_server
        - App.js
    discard-paths: yes
